apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: movies-service-circuit-breaker
spec:
  host: movies-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        http1MaxPendingRequests: 20
        http2MaxRequests: 20
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: monolith-circuit-breaker
spec:
  host: monolith
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        http2MaxRequests: 1
        maxRequestsPerConnection: 1
